package com.github.quantumxiaol.craftmaid.menu;

enum MaidMenuAction {
  STATUS,
  RECALL,
  SET_HOME,
  RETURN_HOME,
  LOOK_AT_PLAYER,
  OPEN_INVENTORY,
  OPEN_EQUIPMENT,
  LIST_ANCHORS,
  SET_FISHING_SPOT,
  SET_REDSTONE_WATCH,
  SET_FARM_REGION_POS1,
  SET_FARM_REGION_POS2,
  SET_POND_REGION_POS1,
  SET_POND_REGION_POS2,
  SET_REDSTONE_REGION_POS1,
  SET_REDSTONE_REGION_POS2,
  FOLLOW_START,
  FOLLOW_STOP,
  GUARD_START,
  GUARD_STOP,
  GUARD_HERE,
  FISHING_PLACEHOLDER,
  CLOSE
}
