package com.github.quantumxiaol.craftmaid.menu;

enum MaidMenuAction {
  STATUS,
  RECALL,
  SET_HOME,
  RETURN_HOME,
  LOOK_AT_PLAYER,
  OPEN_INVENTORY,
  OPEN_EQUIPMENT,
  FOLLOW_START,
  FOLLOW_STOP,
  GUARD_START,
  GUARD_STOP,
  GUARD_HERE,
  FISHING_PLACEHOLDER,
  CLOSE
}
